# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('identify', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
