# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pic_path',
            new_name='img_name',
        ),
    ]
