# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-01 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0003_auto_20180817_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='introduction',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
