# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-13 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0007_auto_20180913_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='timestamp',
        ),
    ]
