# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-14 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collection', '0008_remove_article_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='img_name',
            field=models.TextField(max_length=1000),
        ),
    ]
